apiVersion: v1 
kind: Service 
metadata:
  name: myfrontend-loadbal
  labels:
    tier: frontend
spec:
 type: LoadBalancer
 selector:
  tier: frontend
 ports:
   - name: http
     port: 80
     targetPort: 80
      