apiVersion: apps/v1
kind: Deployment 
metadata:
  name: mysql
spec:
 replicas: 1
 selector: 
  matchLabels:
    app: mysql
 strategy:
  type: Recreate
 template:
  metadata:
   labels:
     app: mysql
  spec:
   containers:
     - name: mysql 
       image: mysql:5.6
       env: 
         - name: MYSQL_ROOT_PASSWORD
           value: dbpassword11
       ports:
         - containerPort: 3306
       volumeMounts:
         - mountPath: /var/lib/mysql
           name: mysql-peristent-storage
         - mountPath: /docker-entrypoint-initdb.d
           name: usermanagement-dbcreation-script         
   volumes:
     - name: mysql-peristent-storage
       persistentVolumeClaim:
          claimName: azure-managed-disk-pvc
     - name: usermanagement-dbcreation-script
       configMap:
          name: usermanagement-dbcreation-script  
     
    