apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managedpremium-retain
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  storageaccounttype: Premium_LRS
  kind: managed 